version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      - echo "Downloading data from GitHub"
      - git clone https://github.com/liveu-cloudops/git-s3.git
  build:
    commands:
      - echo "Uploading data to S3"
      - aws s3 sync . s3://tatva-test-2/
